### ISSUE TITLE
Built-in off() method

### ISSUE THREAD

**Issue by hufftheweevil** [lopelex/harmony-websocket#1]
First off, thanks for creating this API. It's exactly what so many of us have been looking for, and I'm sure it will gain a lot of popularity very soon.

I'm wondering if a `.off()`  method would be helpful for a lot of people. It isn't always readily clear that doing `.startActivity('1')` is the code that is necessary to turn off whatever activity is currently running.

Other than that, I like how it's very simple, modern, and straight-forward!

**Comment by lopelex** [comment]
You can simply extend this class to add new methods or you can make a pull request. Thank you for your recognition.
