### ISSUE TITLE
Firmware 4.15.250 : error 417

### ISSUE THREAD

**Issue by nicoduj** [lopelex/harmony-websocket#4]
Hi,

The latest hub update that was released yesterday broke the initial http request I think and we get a 417 http code .

I will check but just wanted you to know. I took a look at the headers of the app (since it was not updated) and noticed some difference but nothing very « important » except if they now analyse the referer (which would be not good ;) ) :

POST / HTTP/1.1
Host: 192.168.1.42:8088
Content-Type: application/json
Origin: http://sl.dhg.myharmony.com
Accept-Encoding: gzip, deflate
Connection: keep-alive
Accept: */*
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16D57 HClient/5.6 (iOS,12.1.4,iPhone) Version/6.0 Safari/8536.25
Referer: http://sl.dhg.myharmony.com/mobile/2/production/_fr.mobile.html?is321&locale=fr-FR&clientId=Blabla&hubName=salon&sessionId=Blabla&lipClientId=Blabla&hubIP=192.168.1.42&settings&discoveryUrl=http://svcs.myharmony.com/Discovery/Discovery.svc&susChannel=Production
Content-Length: 69
Accept-Language: fr-fr

**Comment by lopelex** [comment]
Maybe it's enough to put the origin on http://sl.dhg.myharmony.com.

**Comment by lopelex** [comment]
Or this brings us further: https://github.com/swissmanu/harmonyhubjs-client/blob/develop/lib/login/auth.js

**Comment by reneboer** [comment]
Hi Nico,
I maintain a plugin for the Vera platform that talks to the Hub and found the solution works without the referer. I just changed the origin and the command  to setup.account?getProvisionInfo. The remote_id can then be found in the activeRemoteId. 
It may brake again on a next Harmony release, but for now I got mine working again.

**Comment by lopelex** [comment]
Thank you reneboer, I've already supposed something like that.

**Comment by lopelex** [comment]
Now only to distinguish between old and new firmware.

**Comment by reneboer** [comment]
I saw the same command in a trace I did back in 2014, so I am assuming it works on the 206 version as well. Not in a position to test though as I only have one Hub and that is now on 250.

**Comment by lopelex** [comment]
Well, make a pull request I'll take it in.

**Comment by lopelex** [comment]
Of course only if you want to.

**Comment by reneboer** [comment]
My own plugin is coded in LUA, so quite different from yours. I can make a request and try, but I cannot test it.

**Comment by nicoduj** [comment]
The header I sent was made with 206 firmware and latest harmony app on iOS : so if it works with this header (without referer) and the new body / response you modified on latest firmware revision I think you can release the modification.

I will test this evening !

**Comment by nicoduj** [comment]
I can confirm it works with version 206 also. 
Just  a thing : I think you should remove the console.log in a next release :) 

Thank you very much for a so fast update !

**Comment by stoneobscurity** [comment]
i'm still getting the 417 error with the .250 firmware in the node-red websocket.

**Comment by stoneobscurity** [comment]
name: 'StatusCodeError',
  statusCode: 417,
  message: '417 - {"code":"417"}',
  error: { code: '417' },
  options: 
   { url: 'http://10.11.99.17:8088',
     method: 'POST',
     timeout: 5000,
     headers: 
      { 'Content-type': 'application/json',
        Accept: 'text/plain',
        Origin: 'http//:localhost.nebula.myharmony.com' },
     json: true,
     body: { id: 0, cmd: 'connect.discoveryinfo?get', params: {} },
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },

look at that eff'ed up localhost URL.
