### ISSUE TITLE
delay is not being honored

### ISSUE THREAD

**Issue by stephack** [lopelex/harmony-websocket#7]
I apologize in advance for adding this issue here but I could not find a way to create this issue under here
https://github.com/lopelex/node-red-contrib-harmony

The sendCommandsWithDelay does not seem to be implemented. Please advise.
Thanks, Stephan

**Comment by lopelex** [comment]
I do not know exactly what you mean.
In HWS command sendCommandsWithDelay is addressed as soon as you set the delay bigger 0.
See https://github.com/lopelex/node-red-contrib-harmony/blob/master/harmony/hub.js#L236.
![Bildschirmfoto 2019-05-29 um 17 24 13](https://user-images.githubusercontent.com/577670/58569621-c109ca80-8236-11e9-9b2d-901a1ad58027.png)

**Comment by stephack** [comment]
I have tried many values in the 10's , 100's and 1000's and there is no perceivable delay to the command.

**Comment by lopelex** [comment]
The delay time indicates how long the command is held. 
So how long the IR signal is sent. The delay is not a pause between the commands.
https://github.com/lopelex/harmony-websocket/blob/master/lib/harmony-websocket.js#L313

**Comment by stephack** [comment]
Ahh so it's the equivalent to holding down the volume button for x seconds, correct?
If so, can I make a feature request to insert a delay (before or after..doesn't matter) to the command being sent?

**Comment by lopelex** [comment]
Of course I'm ready for it.
But please read this through:
https://github.com/lopelex/harmony-websocket/pull/2

**Comment by lopelex** [comment]
https://github.com/lopelex/node-red-contrib-harmony/commit/d95a491382a94031025c4b57054de1d2663c3784

**Comment by lopelex** [comment]
ready for testing
![Bildschirmfoto 2019-05-30 um 12 02 50](https://user-images.githubusercontent.com/577670/58625580-0b408980-82d3-11e9-876d-938a8128f4b6.png)
